# Function to add quotes around the comments generated by TestSelectionForMechTurk.ipynb
# Because Mech Turk wants a csv file & commas in the comments made their system unhappy

import pandas as pd
import re


def addquotes(infilename = 'MT_OnlineHateSp_TestSub.csv', outfilename = 'MT_OnlineHate_Test_corrected.csv'):
    #read data
    df = pd.read_csv(infilename)

    #add quotes around "body" & call new column comment
    df['comment'] = ' "' + df.body + '" '

    # delete 'body', 'Unnamed: 0' columns
    del df['body']
    del df['Unnamed: 0']

    # get rid of the funny characters
#    df['comment'] = re.sub(^\w "'!?],'', df['comment'])

    # Convert bytes to unicode
    for i in range(len(df)):
        df.comment[i] = df.comment[i].decode('utf8').encode('ascii', 'ignore')
        #df.comment[i] = df.comment[i].encode('ascii', 'ignore')

    

    #read to file
    df.to_csv(outfilename, encoding = 'utf-8')


if __name__ == "__main__":
    addquotes()
